services:
  wallet-app:
    build: ./
    command: /bin/sh -c "migrate -path ./schema -database 'postgres://postgres:qwerty@db:5432/postgres?sslmode=disable' up && ./wallet"
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
  db:
    restart: always
    image: postgres
    volumes:
      - wallet-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432
volumes:
  wallet-db-data: